server:
  port: 8080

spring:
  application:
    name: demo-form-builder
  data:
    mongodb:
      uri: mongodb://localhost:27017/dynamic_form_db
    redis:
      host: localhost
      port: 6379
      password: Test
      connect-timeout: 2000 # milliseconds
      client-name: form-builder

  cache:
    type: redis
    redis:
      time-to-live: 86400000 # 24 hours in milliseconds
      cache-null-values: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: form-builder-group
      auto-offset-reset: earliest
    form-topic: form-events
    submission-topic: form-submissions
    template-topic: template-events
    analytics-topic: analytics-events

  # Disable Kafka auto-configuration if needed
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration


# Resilience settings
resilience:
  redis:
    retry:
      max-attempts: 3
      backoff:
        initial-interval: 1000
        multiplier: 2
        max-interval: 5000


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %5p | %X{traceId} | %msg%n"
  level:
    root: info
    io.lettuce.core: DEBUG
    org.springframework.data.redis: DEBUG