package com.generic.enumration;

public enum ElementType {
    TEXT, TEXTAREA, NUMBER, EMAIL, PASSWORD, SELECT, MULTI_SELECT,
    CHECKBOX, RADIO, DATE, TIME, DATETIME, FILE, IMAGE, SIGNATURE,
    SECTION, DIVIDER, RICH_TEXT, ADDRESS, PHONE, URL, RATING, SLIDER
}
